language: python
python:
  - "3.8"
matrix:
  include:

  - name: test sphinx docs

  # Testing Python versions
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"

addons:
  apt:
    packages:
      - pandoc
      - librsvg2-bin
# command to install dependencies
install:
  - python3 --version
  - python3 -m pip install Sphinx
  - python3 -m pip install .
  - python3 -m pip install $(grep -iv bibtex docs/requirements.txt)
  - python3 -m pip install sphinxcontrib-bibtex$BIBTEX
# command to run tests
script:
  - python3 -m nbsphinx
  - python3 -m sphinx docs/ docs/_build/ -W -b html
